from datetime import datetime
from SoftLayer.sltypes.Entity import Entity

class Dns_Message(Entity):
    """The SoftLayer_Dns_Message data type contains information for a single message generated by the SoftLayer DNS
system. SoftLayer_Dns_Messages are typically created during the secondary DNS transfer process."""
    createDate: datetime
    id_: int
    message: str
    priority: str
