from SoftLayer.sltypes.Ticket.Chat.TranscriptLine import Ticket_Chat_TranscriptLine
from SoftLayer.sltypes.Ticket_Chat_TranscriptLine import Ticket_Chat_TranscriptLine

class Ticket_Chat_TranscriptLine_Customer(Ticket_Chat_TranscriptLine):
    pass
