name: slcli
adopt-info: slcli
summary: A CLI tool to interact with the SoftLayer API.
description: |
    A command-line interface is also included and can be used to manage various SoftLayer products and services.

license: MIT

base: core22
grade: stable 
confinement: strict

assumes:
  - command-chain

apps:
  slcli:
    command: bin/slcli
    command-chain: 
      - bin/homeishome-launch        
    environment: 
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - network-bind
     
parts: 
  slcli:
    source: https://github.com/softlayer/softlayer-python
    source-type: git
    plugin: python
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//')"
    
    build-packages:
      - python3
      
    stage-packages:
      - python3

  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch     
