# https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# Trusted Publisher stuff: https://docs.pypi.org/trusted-publishers/adding-a-publisher/

name: Release to PyPi

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/SoftLayer/
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

